In [42]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

In [43]:
data = pd.read_csv("MagicBricks.csv")

In [44]:
data.head()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0

In [45]:
data.fillna(0, inplace = True)

In [46]:
data.shape

(1259, 11)

In [47]:
enc = LabelEncoder()
data.iloc[:,4] = enc.fit_transform(data.iloc[:,1])

In [48]:
data.head()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,2,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,0.0
1,750.0,2,2.0,Semi-Furnished,1,1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,1,1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,1,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,1,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0

In [49]:
X = data.iloc[:,[0,1,2,3,4,5,7,8,9,10]]

In [50]:
X.tail(60)

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Status,Transaction,Type,Per_Sqft
1199,2520.0,3,3.0,Unfurnished,2,0.0,Ready_to_move,New_Property,Builder_Floor,0.0
1200,1700.0,3,4.0,Unfurnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,0.0
1201,1800.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,24166.0
1202,6000.0,5,5.0,Semi-Furnished,4,3.0,Ready_to_move,New_Property,Apartment,30000.0
1203,1800.0,4,4.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,30000.0
1204,2000.0,3,3.0,Unfurnished,2,2.0,Ready_to_move,Resale,Apartment,30000.0
1205,2066.0,4,4.0,Unfurnished,3,2.0,Almost_ready,New_Property,Builder_Floor,30000.0
1206,2050.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,30000.0
1207,1100.0,3,3.0,Unfurnished,2,2.0,Ready_to_move,Resale,Apartment,30000.0
1208,4500.0,4,4.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,30000.0
1209,4500.0,4,5.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,170000.0
1210,6500.0,4,5.0,Unfurnished,3,3.0,Ready_to_move,New_Property,Builder_Floor,170000.0
1211,4350.0,4,6.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Apartment,170000.0
1212,1750.0,3,3.0,Unfurnished,2,2.0,Ready_to_move,Resale,Builder_Floor,170000.0
1213,3600.0,4,4.0,Semi-Furnished,3,2.0,Almost_ready,New_Property,Builder_Floor,18055.0
1214,1200.0,2,2.0,Furnished,1,1.0,Ready_to_move,Resale,Builder_Floor,18055.0
1215,1500.0,3,4.0,Unfurnished,2,2.0,Ready_to_move,Resale,Builder_Floor,18055.0
1216,2250.0,4,4.0,Unfurnished,3,3.0,Ready_to_move,New_Property,Builder_Floor,18055.0
1217,1800.0,3,4.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,18055.0
1218,1600.0,3,4.0,Semi-Furnished,2,2.0,Ready_to_move,Resale,Builder_Floor,18055.0
1219,2800.0,4,5.0,Semi-Furnished,3,3.0,Ready_to_move,New_Property,Builder_Floor,25000.0
1220,1700.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Apartment,25000.0
1221,2400.0,4,5.0,Unfurnished,3,1.0,Ready_to_move,Resale,Builder_Floor,25000.0
1222,1980.0,3,4.0,Unfurnished,2,1.0,Almost_ready,New_Property,Apartment,17677.0
1223,2100.0,4,5.0,Semi-Furnished,3,1.0,Ready_to_move,New_Property,Builder_Floor,17677.0
1224,5400.0,4,4.0,Unfurnished,3,2.0,Ready_to_move,Resale,Builder_Floor,17677.0
1225,1250.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,17677.0
1226,2300.0,4,4.0,Semi-Furnished,3,1.0,Ready_to_move,New_Property,Builder_Floor,17677.0
1227,2700.0,4,4.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,37037.0
1228,1450.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,New_Property,Builder_Floor,37037.0
1229,2097.0,3,3.0,Unfurnished,2,0.0,Ready_to_move,Resale,Builder_Floor,0.0
1230,1250.0,3,3.0,Semi-Furnished,2,1.0,Almost_ready,New_Property,Builder_Floor,0.0
1231,1600.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,20938.0
1232,2600.0,4,5.0,Semi-Furnished,3,3.0,Ready_to_move,New_Property,Builder_Floor,20938.0
1233,1700.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,20938.0
1234,1116.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,20938.0
1235,1070.0,2,3.0,Semi-Furnished,1,1.0,Ready_to_move,New_Property,Builder_Floor,20938.0
1236,1200.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,New_Property,Builder_Floor,20938.0
1237,1200.0,3,3.0,Unfurnished,2,1.0,Ready_to_move,New_Property,Builder_Floor,18333.0
1238,1200.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,New_Property,Builder_Floor,18333.0
1239,1450.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,18333.0
1240,1000.0,2,2.0,Semi-Furnished,1,1.0,Ready_to_move,Resale,Apartment,18333.0
1241,2430.0,4,4.0,Furnished,3,5.0,Ready_to_move,Resale,Builder_Floor,18333.0
1242,945.0,2,1.0,Unfurnished,1,5.0,Ready_to_move,Resale,Apartment,6878.0
1243,1650.0,3,3.0,Unfurnished,2,5.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1244,1350.0,3,2.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,6878.0
1245,2625.0,4,5.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1246,1800.0,4,4.0,Semi-Furnished,3,2.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1247,125.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1248,1440.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1249,1900.0,3,4.0,Semi-Furnished,2,2.0,Ready_to_move,New_Property,Builder_Floor,6878.0
1250,1800.0,3,3.0,Semi-Furnished,2,2.0,Ready_to_move,Resale,Builder_Floor,6878.0
1251,1200.0,3,2.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,12916.0
1252,1800.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,12916.0
1253,1200.0,3,3.0,Semi-Furnished,2,1.0,Ready_to_move,Resale,Builder_Floor,12916.0
1254,4118.0,4,5.0,Unfurnished,3,3.0,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,2,3.0,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,2,3.0,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,1,1.0,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,2,1.0,Ready_to_move,New_Property,Builder_Floor,12916.0

In [51]:
y = data.Price

In [52]:
y.tail(60)

1199     47500000
1200     45000000
1201     43500000
1202    180000000
1203     80000000
1204     37500000
1205     60000000
1206     71000000
1207     18500000
1208     70000000
1209     85000000
1210    190000000
1211    135000000
1212     35000000
1213     65000000
1214     27500000
1215     45000000
1216    100000000
1217     47000000
1218     27500000
1219     70000000
1220     36500000
1221     65000000
1222     35000000
1223     56000000
1224    110000000
1225     24000000
1226    102500000
1227    100000000
1228     45000000
1229     29000000
1230     25500000
1231     33500000
1232     62500000
1233     47500000
1234     14700000
1235     18000000
1236     22500000
1237     22000000
1238     22200000
1239     22500000
1240      7500000
1241     30000000
1242      6500000
1243     35000000
1244     17500000
1245     60000000
1246     40000000
1247     11500000
1248     22500000
1249     28500000
1250     29000000
1251     15500000
1252     26000000
1253     16500000
1254     55000000
1255     12500000
1256     17500000
1257     11500000
1258     18500000
Name: Price, dtype: int64

In [53]:
X = pd.get_dummies(X, drop_first =True)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X,y ,test_size =0.3)

In [55]:
X_train

,Area,BHK,Bathroom,Locality,Parking,Per_Sqft,Furnishing_Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,Status_Ready_to_move,Transaction_Resale,Type_Apartment,Type_Builder_Floor
1121,800.0,2,2.0,1,2.0,11905.0,0,1,0,1,1,1,0
133,900.0,2,2.0,1,2.0,7000.0,0,0,1,1,1,0,1
117,1350.0,3,3.0,2,1.0,15556.0,0,1,0,1,1,0,1
291,1150.0,3,3.0,2,1.0,20930.0,0,1,0,1,0,0,1
418,765.0,3,2.0,2,1.0,5794.0,0,1,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,1250.0,3,2.0,2,2.0,0.0,0,1,0,1,1,1,0
1196,1200.0,2,2.0,1,1.0,18000.0,0,0,1,1,1,1,0
627,800.0,3,2.0,2,1.0,10943.0,0,0,1,1,1,0,1
701,1400.0,3,3.0,2,1.0,12500.0,1,0,0,1,1,1,0
28,28.0,2,2.0,1,1.0,8750.0,1,0,0,1,0,1,0

In [56]:
linear = LinearRegression()
linear.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [59]:
pred = linear.predict(X_test)

In [61]:
r2_score(y_test, pred)

0.6027522236313524